export const FETCH_SINGLE_LOCATION_REQUEST = "FETCH_SINGLE_LOCATION_REQUEST";
export const FETCH_SINGLE_LOCATION_SUCCESS = "FETCH_SINGLE_LOCATION_SUCCESS";
export const FETCH_SINGLE_LOCATION_FAILURE = "FETCH_SINGLE_LOCATION_FAILURE";