export const FETCH_CHARACTERS_BY_NAME_REQUEST = "FETCH_CHARACTERS_BY_NAME_REQUEST";
export const FETCH_CHARACTERS_SUCCESS = "FETCH_CHARACTERS_SUCCESS";
export const FETCH_CHARACTERS_FAILURE = "FETCH_CHARACTERS_FAILURE";